### ISSUE TITLE
Network Drives not working

### ISSUE THREAD

**Issue by Mr-Zero88** [Neolyon0101/MyFilesXProject#1]
When i want to acces a virtual drive aka Z: that is mapped to a network SMB server it is just an emty folder.
Also it is shown as a "usb-drive" and not the name of the virtual drive link aka "MyNASS".

**Comment by Neolyon0101** [comment]
Hi Mr-Zero88, at this moment that feature is not supported, I have been planed to added but by now, I do not have enough time. I will add it as soon I can.
