### ISSUE TITLE
Please add path largest 255 chars in path

### ISSUE THREAD

**Issue by korenevskiy** [Neolyon0101/MyFilesXProject#2]
The standard explorer limit is 255 characters in the full folder path.
All partition formats do not have this restriction. And also the operating system does not have this restriction. Only the standard Windows Explorer has a restriction.
I would love to use your browser. By default, all applications also have this restriction. But if you had set parameters in the application configuration to remove the restriction on the length of the file path more than 255 characters. I would use your application to back up working files.
You need to be able to: Copy, Cut, Create folders with a large number of characters in the path.
But so far, there is no point in your application.

**Comment by Neolyon0101** [comment]
@korenevskiy this feature could be problematic (I think), due to some file APIs that my files-x use might have some validations in order to prevent create files or folder with it. It is possible (I think too), but I need time and some tests. I will see what can I do.

**Comment by Neolyon0101** [comment]
> The standard explorer limit is 255 characters in the full folder path.
> All partition formats do not have this restriction. And also the operating system does not have this restriction. Only the standard Windows Explorer has a restriction.
> I would love to use your browser. By default, all applications also have this restriction. But if you had set parameters in the application configuration to remove the restriction on the length of the file path more than 255 characters. I would use your application to back up working files.
> You need to be able to: Copy, Cut, Create folders with a large number of characters in the path.
> But so far, there is no point in your application.

@korenevskiy this feature could be problematic (I think), due to some file APIs that my files-x use might have some validations in order to prevent create files or folder with it. It is possible (I think too), but I need time and some tests. I will see what can I do.

**Comment by Neolyon0101** [comment]
I have been decided that I will not  do this change, in order to respect this rule on Windows.  I hope you understand, sorry.
