### ISSUE TITLE
App window won't move

### ISSUE THREAD

**Issue by codingU4EA** [Neolyon0101/MyFilesXProject#4]
Same problem with both the free and paid version . . . 

Once I open the app, I can't move the app window. As one would normally would, I use my mouse to grab the title bar but the app window won't move. 

Using Windows 10, version 10.0.19043 Build 19043.

Thanks.

**Comment by W-Shih** [comment]
Same problem with Windows 10 - 21H1 - 19043.1202

**Comment by mingyong-g** [comment]
Same problem with Windows 10 - 21H1 - 19042

**Comment by Rantarus** [comment]
Hi. I have same problem on my Windows10 - but i can move my app window. I have to grab app window i a specific place.
Try to grab My File-X window 5 mm on the left from the minimize button on the top bar.  It works for me. It's annoying, but it's working :)

**Comment by Neolyon0101** [comment]
Hi you all!, I have been working on a solution, but I have not managed to solve anything, what I can think of is to modify the design of the app a bit, that is, separate and move the title bar up, it is the only solution that I can think of for now. I have been busy with other projects, so I ask for your understanding, and I hope to make the change as soon as possible. Sorry for the inconvenience and I hope you are doing the best. Regards!

**Comment by KazBrekker1** [comment]
I have the same problem, but when I press and hold right beside the minimizing button, it moves.
So maybe it has to do with the width of the container that holds the top right three buttons?

Good luck and thank you for the effort👌

**Comment by Neolyon0101** [comment]
Due to I have been release a new version and I tested it, this issue has been resolve!, please install update 7.2.1 or higher!
