### ISSUE TITLE
Translation Error(Chinese translation)

### ISSUE THREAD

**Issue by 2catycm** [Neolyon0101/MyFilesXProject#7]
how to see the problem:
1. Choose Chinese 
![图片](https://user-images.githubusercontent.com/41530341/141745891-0e30c956-7252-41fc-b821-812f2207a00b.png)

2. click again
![图片](https://user-images.githubusercontent.com/41530341/141746163-910ae1ab-496a-4e52-9466-75cf240344f5.png)

Korean is not "汉语" in Chinese, it is “韩语” or “朝鲜语”.
What make the problem worse, “汉语” actually means “Chinese”.

**Comment by Neolyon0101** [comment]
@2catycm Ok, thank you for the observation. I will correct it soon.
